"use client";
import { X, Link2 } from "lucide-react";
import type { SelectedEdge } from "./GraphViewer";

export function EdgeInspector({ edge, onClose }: { edge: SelectedEdge; onClose: () => void }) {
  const isSummary = edge.source.startsWith("Summary/") || edge.target.startsWith("Summary/");
  const title = isSummary ? "Display grouping" : "FHIR reference";
  return <aside className="h-full p-4 space-y-4" aria-label={`${title} details`}>
    <div className="flex items-center justify-between"><h3 className="flex items-center gap-2 font-semibold"><Link2 className="size-4" />{title}</h3><button onClick={onClose} aria-label="Close edge details"><X className="size-4" /></button></div>
    <p className="text-sm text-muted-foreground">{isSummary
      ? "This edge groups resources for display in the patient overview. It is generated by the interface and is not a FHIR resource reference."
      : "This relationship comes from an explicit reference in a FHIR resource. It does not establish clinical causation."}</p>
    <dl className="space-y-3 text-sm"><div><dt className="text-muted-foreground">Source</dt><dd className="font-medium">{edge.sourceNodeLabel}</dd><dd className="font-mono text-xs break-all">{edge.source}</dd></div><div><dt className="text-muted-foreground">Relationship</dt><dd className="font-mono">{edge.label}</dd></div><div><dt className="text-muted-foreground">Target</dt><dd className="font-medium">{edge.targetNodeLabel}</dd><dd className="font-mono text-xs break-all">{edge.target}</dd></div></dl>
  </aside>;
}
